name = "AdventOfCode"
uuid = "acf53f78-ff67-48ba-a28a-63807685f0f6"
authors = ["Matt Boler <boler.matthew@gmail.com>"]
version = "0.1.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[compat]
DelimitedFiles = "1.9.1"
